version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fatLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wra2jxbz3nim"
s3_prefix = "fatLambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Example=\"\""
